#############################################
# Default configuration file for pyBNA
#
# Optional settings are commented out
# In general, optional parameters can be
# deduced through code so you'd only
# want to specify these if you have an
# unusual circumstance
#############################################
# srid: 4326
units: mi # either km (metric) or mi (imperial), default is "mi" if not given

db:
    user: "gis"
    password: "gis"
    host: "localhost"
    dbname: "bna"

bna:
    boundary:
        table: "neighborhood_boundary"
        geom: "geom"

    blocks:
        table: "neighborhood_census_blocks"
        # schema: "generated"
        uid: "blockid10"
        population: "pop10"
        geom: "geom"
        roads_tolerance: 15     # determines whether a road is considered "connected" to a block
        min_road_length: 30     # determines whether a road is considered "connected" to a block

    network:
        roads:
            table: "neighborhood_ways"
            geom: "geom"
            uid: "road_id"
            source_column: "intersection_from"
            target_column: "intersection_to"
            oneway: {name: "one_way", forward: "ft", backward: "tf"}
            stress:
                segment:
                    forward: ft_seg_stress
                    backward: tf_seg_stress
                crossing:
                    forward: ft_int_stress
                    backward: tf_int_stress
        intersections:
            table: "neighborhood_ways_intersections"
            geom: "geom"
            uid: "int_id"
            cluster_distance: 5
        edges:
            table: "neighborhood_ways_net_link"
            source_column: "source_vert"
            target_column: "target_vert"
            stress_column: "link_stress"
            cost_column: "link_cost"
            id_column: link_id
        nodes:
            table: "neighborhood_ways_net_vert"
            id_column: vert_id

    connectivity:
        table: "neighborhood_connected_census_blocks"
        source_column: "source_blockid10"
        target_column: "target_blockid10"
        max_distance: 2680
        max_detour: 25      # given as a whole number percentage (i.e. 25 == 25%)
        detour_agnostic_threshold: 400  # under this distance, detour is ignored
        max_stress: 1

    destinations:
      - name: people
        weight: 15
        table: neighborhood_census_blocks
        method: percentage
        datafield: pop10
        maxpoints: 100
        breaks: {0.03: 10, 0.2: 40, 0.5: 80}
        uid: gid
        blocks: blockid10
      - name: opportunity
        weight: 20
        subcats:
          - name: employment
            weight: 35
            table: neighborhood_census_block_jobs
            method: percentage
            datafield: jobs
            maxpoints: 100
            breaks: {0.03: 10, 0.2: 40, 0.5: 80}
            uid: id
            blocks: blockid10
          - name: schools
            weight: 35
            table: neighborhood_schools
            method: count
            maxpoints: 100
            breaks: {1: 30, 2: 20, 3: 20}
            uid: id
            blocks: blockid10
          - name: colleges
            weight: 10
            table: neighborhood_colleges
            method: count
            maxpoints: 100
            breaks: {1: 70}
            uid: id
            blocks: blockid10
          - name: universities
            weight: 20
            table: neighborhood_universities
            method: count
            maxpoints: 100
            breaks: {1: 70}
            uid: id
            blocks: blockid10
      - name: core_services
        weight: 20
        subcats:
          - name: doctors
            weight: 20
            table: neighborhood_doctors
            method: count
            maxpoints: 100
            breaks: {1: 40, 2: 20, 3: 10}
            uid: id
            blocks: blockid10
          - name: dentists
            weight: 10
            table: neighborhood_dentists
            method: count
            maxpoints: 100
            breaks: {1: 40, 2: 20, 3: 10}
            uid: id
            blocks: blockid10
          - name: hospitals
            weight: 20
            table: neighborhood_hospitals
            method: count
            maxpoints: 100
            breaks: {1: 70}
            uid: id
            blocks: blockid10
          - name: pharmacies
            weight: 10
            table: neighborhood_pharmacies
            method: count
            maxpoints: 100
            breaks: {1: 40, 2: 20, 3: 10}
            uid: id
            blocks: blockid10
          - name: supermarkets
            weight: 25
            table: neighborhood_supermarkets
            method: count
            maxpoints: 100
            breaks: {1: 60, 2: 20}
            uid: id
            blocks: blockid10
          - name: social_services
            weight: 15
            table: neighborhood_social_services
            method: count
            maxpoints: 100
            breaks: {1: 70}
            uid: id
            blocks: blockid10
      - name: recreation
        weight: 15
        subcats:
          - name: parks
            weight: 40
            table: neighborhood_parks
            method: count
            maxpoints: 100
            breaks: {1: 30, 2: 20, 3: 20}
            uid: id
            blocks: blockid10
        #   - name: trails
        #     weight: 35
        #     table: neighborhood_paths
        #     method: count
        #     maxpoints: 100
        #     breaks: {1: 70, 2: 20}
        #     method: trails
        #     blocks: blockid10
          - name: community_centers
            weight: 25
            table: neighborhood_community_centers
            method: count
            maxpoints: 100
            breaks: {1: 40, 2: 20, 3: 10}
            uid: id
            blocks: blockid10
      - name: retail
        weight: 15
        table: neighborhood_retail
        method: count
        maxpoints: 100
        breaks: {1: 40, 2: 20, 3: 10}
        uid: id
        blocks: blockid10
      - name: transit
        weight: 15
        table: neighborhood_transit
        method: count
        maxpoints: 100
        breaks: {1: 60}
        uid: id
        blocks: blockid10
